### PR TITLE
Added methods and tests related to insufficient material

### PR DESCRIPTION
**Pull request by dlbbld**
Insufficient material according python chess implementation. Fixing existing method and adding the "one-sided" insufficient material check.

### CODE REVIEW

**Comment by dlbbld** [comment]
Closing the issue as it became stale.

**Comment by bhlangonijr** [comment]
Hi @dlbbld why have you closed this PR and all the related issues?

**Comment by dlbbld** [comment]
Hi Carlos
From my perspective, some of the issues should be addressed within a certain timeframe. For some issues, now it is just too long. They are stale. I see no reason to track forever.
On the other side, there was zero feedback from your side about the progress and regarding a new issue. I do not like to work as such. For this reason, I am untracking the issues.
best regards, Daniel

**Comment by bhlangonijr** [comment]
Hi Daniel @dlbbld, 
I think you have made some good contributions to this public chess repository. I apologize for the lingering issues and PRs waiting on my feedbacks/actions. Sometimes I just miss the notifications as in this particular case. I kindly ask you to reconsider contributing to this project with your valuable ideas and suggestions. If you are interested I can add you as a collaborator so that you have more autonomy for adding your changes. I am also adjusting the project notification so that I don't miss any. Let me know what you think.

**Comment by dlbbld** [comment]
Hi Ben
I think your comment is giving me too much credit on the one side. Your API is fine overall and doesn't depend on my comments. I mentioned some issues you addressed, but some issues you did not give much attention on the other side.

I consider the insufficient material related methods essential for a chess API. There wasn't any feedback for adding the one-sided insufficient material methods for determining the draw on timeout. There was also no feedback regarding the bug in the existing method for determining both sided insufficient material.

For my purpose, I need to use workarounds in this relation, which I can do for some releases, but not for half a year (#41). So I am closing this to save me work. If other users are interested in these features, they can request them. If not requested, there seems no public interest in this, so then it's also fine.
Daniel

**Pull request closed without merging**
